# CMD instructions is  used for specifying the default command to run within a container when no command is provided during the container startup. 

FROM almalinux:9
RUN dnf install nginx -y
CMD ["nginx", "-g", "daemon off;"]